// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANV9AQMtCxoi-vOPLxddlw_Fd4JPT6LyY',
    appId: '1:751233585713:web:b7e39c68742bd244a97b10',
    messagingSenderId: '751233585713',
    projectId: 'coil-50528',
    authDomain: 'coil-50528.firebaseapp.com',
    storageBucket: 'coil-50528.firebasestorage.app',
    databaseURL: 'https://coil-50528-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqeOrAoIPgBzOVvfXc6NP93_KbHwXMl0',
    appId: '1:751233585713:android:d39edcd910ac1c08a97b10',
    messagingSenderId: '751233585713',
    projectId: 'coil-50528',
    storageBucket: 'coil-50528.firebasestorage.app',
    databaseURL: 'https://coil-50528-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvwy72IH_gaMZ0eGjrkQaBKbrTEPeigU',
    appId: '1:751233585713:ios:767585b42bdad187a97b10',
    messagingSenderId: '751233585713',
    projectId: 'coil-50528',
    storageBucket: 'coil-50528.firebasestorage.app',
    iosBundleId: 'com.iter.ai',
    iosClientId: '751233585713-tgffet0qbu9em9mlhsbh84jiqrh24a8o.apps.googleusercontent.com',
    databaseURL: 'https://coil-50528-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
